#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032proj
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Water Heater Project
# Description: Water Heater Project  
### END INIT INFO

boardId=`cat /sys/devices/virtual/dmi/id/board_name`

case "$1" in
  start|restart|force-reload)
    # pwm3 = IO3 in Galileo Gen1, IO5 in Galileo Gen2,
    if [ ! -d /sys/class/pwm/pwmchip0/pwm3 ] ; then
        echo -n "3" > /sys/class/pwm/pwmchip0/export
    fi
    chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
    chmod g+w /sys/class/pwm/pwmchip0/device/pwm_period
    chgrp pwm /sys/class/pwm/pwmchip0/pwm3/period
    chmod g+w /sys/class/pwm/pwmchip0/pwm3/period
    chgrp pwm /sys/class/pwm/pwmchip0/pwm3/duty_cycle
    chmod g+w /sys/class/pwm/pwmchip0/pwm3/duty_cycle
    chgrp pwm /sys/class/pwm/pwmchip0/pwm3/enable
    chmod g+w /sys/class/pwm/pwmchip0/pwm3/enable

    case $boardId in
      "Galileo")
	# Mux 31 = 1 --> IO2 via Cypress 
      	if [ ! -d /sys/class/gpio/gpio31 ] ; then
	    echo -n "31" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio31/direction
	echo -n "1" > /sys/class/gpio/gpio31/value
	
	# IO2 --> GPIO 32 (Cypr)
	if [ ! -d /sys/class/gpio/gpio32 ] ; then
	    echo -n "32" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio32/direction
	echo -n "strong" > /sys/class/gpio/gpio32/drive
	chgrp gpio /sys/class/gpio/gpio32/value
	chmod g+rw /sys/class/gpio/gpio32/value

	# GPIO44 = in = neither pull-up nor pull-down
        if [ ! -d /sys/class/gpio/gpio44 ] ; then
          echo -n "44" > /sys/class/gpio/export
        fi
        echo -n "in" > /sys/class/gpio/gpio44/direction

        # GPIO37 = 0 = AD0
        if [ ! -d /sys/class/gpio/gpio37 ] ; then
          echo -n "37" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio37/direction
        echo -n "0" > /sys/class/gpio/gpio37/value

	# GPIO30 = 1 --> IO3=CY8C9540A   
        if [ ! -d /sys/class/gpio/gpio30 ] ; then
            echo -n "30" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio30/direction
        echo -n "1" > /sys/class/gpio/gpio30/value
    	;;
      "GalileoGen2")
	echo "Support not available for GalileoGen2"
	exit 1
	;;
    esac
    ;;
  stop)
    case $boardId in
      "Galileo")
    	echo -n "in" > /sys/class/gpio/gpio32/direction
    	echo -n "32" > /sys/class/gpio/unexport
	echo -n "31" > /sys/class/gpio/unexport
    	echo -n "44" > /sys/class/gpio/unexport
        echo -n "37" > /sys/class/gpio/unexport
	echo -n "30" > /sys/class/gpio/unexport
	;;
      "GalileoGen2")
    	echo "Support not available for GalileoGen2"
	;;
    esac
    ;;
  status)
    ls -d /sys/class/gpio/gpio*
    echo -n Period:
    case $boardId in
      "Galileo")
        cat /sys/class/pwm/pwmchip0/pwm3/period
        ;;
      "GalileoGen2")
        echo "Support not available for GalileoGen2"
        ;;
    esac
    echo -n Duty Cicle:
    cat /sys/class/pwm/pwmchip0/pwm3/duty_cycle
    echo -n Enable:
    cat /sys/class/pwm/pwmchip0/pwm3/enable
    ;;
  *)
    echo -n "Usage: $0 " 
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
